apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations: 
    kubernetes.io/change-cause: "reduce replicas to 2 and keep version 1.19.0"
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80